#!/bin/bash

# absolute path for public access
url="https://ccmjs.github.io/testsuite/"

# create versions folder if not exists
mkdir -p versions

# create empty subfolder for latest version
rm -rf versions/latest
mkdir versions/latest

# copy relevant folders/files to this subfolder
shopt -s extglob
cp -R !(node_modules|versions|build|favicon.ico|*.html|LICENSE|README.md|package.json|package-lock.json) versions/latest
shopt -u extglob

# replace locale paths that start with '././' with absolute paths
str=s\/\\.\\/\\.\\//${url//\//\\\/}versions\\/latest\\//g
find ./versions/latest -type f -print0 | xargs -0 perl -pi -e $str

# minify CSS files
for i in $(find ./versions/latest -name \*.css); do
  i="${i%.*}"
  csso -i ${i}.css -o ${i}.min.css

  # update paths where minified CSS files are used
  css=${i:1}.css
  css=${css////\\/}
  min=${i:1}.min.css
  min=${min////\\/}
  str=s/${css}/${min}/g
  find ./versions/latest -type f -print0 | xargs -0 perl -pi -e $str
done

# minify JS files
for i in $(find ./versions/latest -name \*.js); do
  i="${i%.*}"
  terser ${i}.js -o ${i}.min.js --comments false --source-map "url='${i}.min.js.map'"
done

# minify MJS files
for i in $(find ./versions/latest -name \*.mjs); do
  i="${i%.*}"
  terser ${i}.mjs -o ${i}.min.mjs --comments false --source-map "url='${i}.min.mjs.map'"
done

# create empty subfolder for specific version
version=$(awk '/@version/{print $3}' ccm.*.js)
rm -rf "versions/${version}"
mkdir "versions/${version}"

# copy folders/files from latest version to specific version
cp -R versions/latest/* "versions/${version}"
